name: offline_web_proxy
description: "Local offline-first proxy server for Flutter WebView."
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  path_provider: ^2.1.5
  shelf: ^1.4.2
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2
